# Generated by Django 4.2.1 on 2023-06-26 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=220)),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=220)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='Project_ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.IntegerField(choices=[(0, 'mini project'), (1, 'main project'), (2, 'live project')])),
                ('description', models.TextField()),
                ('project_title', models.CharField(max_length=220)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectideas.course')),
                ('technology', models.ManyToManyField(blank=True, to='projectideas.technology')),
            ],
            options={
                'verbose_name_plural': 'Project_ideas',
            },
        ),
    ]
